name: Deploy PR to GCS

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Deploy PR to GCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build website
        env:
          URL: https://storage.googleapis.com
          BASE_URL: /saga-docs-prod_public-pr/pr-${{github.event.pull_request.number}}/
        run:
          npm run build

      - name: Setup Google Cloud SDK
        uses: svvsaga/github-actions-public/setup-gcloud@v20.1.1
        with:
          app_root: ./
          environment: PROD

      - name: Deploy to GCS
        run: |
          gsutil cp -r build/* gs://saga-docs-prod_public-pr/pr-${{github.event.pull_request.number}}/

      - name: Link to PR build of docs in comment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            Check how your changes worked out using this url:
            
            https://storage.googleapis.com/saga-docs-prod_public-pr/pr-${{github.event.pull_request.number}}/intro/index.html

            (Note: Deploying docusaurus sites to GCS like this ☝️ without a custom domain is not optimal, so your milage may vary using the link above. E.g. among other things, refresh of pages after navigating around the website does not work.)
